### ISSUE TITLE
Is it possible to build the Flashback source code locally?

### ISSUE THREAD

**Issue by Aarskin** [linkedin/flashback#15]
I'd like to build the source code locally, but when simple cloning and opening the project, I see a plethora of errors:

- Assert cannot be resolved
- ASN1Sequence cannot be resolved to a type
- ASN1Inputstream cannot be resolved to a type
- ASN1EncodableVector cannot be resolved to a type
- ASN1Encodable cannot be resolved to a type
- AfterTest cannot be resolved to a type
- AfterMethod cannot be resolved to a type
- ActionParam cannot be resolved to a type

Any thoughts on how I could clear this up?

**Comment by sf1152** [comment]
how did you build source code? gradle build?

**Comment by Aarskin** [comment]
This was an ignorant comment 🤦‍♂️
