### ISSUE TITLE
Support for single-value headers with a comma

### ISSUE THREAD

**Issue by rickle-msft** [linkedin/flashback#26]
Some headers, such as Date, which, per the HTTP spec, is in RFC 1123 format, are single valued but contain a comma in them. The current method for supporting multi-valued headers splits on commas, which breaks this scenario. Instead of grouping multi-valued headers into one, comma-separated list, we propose maintaining them as separate key-value pairs.

**Comment by sf1152** [comment]
Fixed by @rickle-msft
